### ISSUE TITLE
[백엔드] 소셜로그인 보완

### ISSUE THREAD

**Issue by newbieJanghan** [oxopolitics-internship-for-elice/footprints#50]
- [x] once_token의 필요 여부 고민하고 그대로 둘지 말지 고민
- [x] once_token을 두는 이유가 임시 회원이라면 jwt payload에 status를 보관하는 방법이 있음

**Comment by WinterKwon** [comment]
현재 상황에서 once token 없이 최초 로그인시 카카오 동의로 로그인되도록 로직 수정하겠습니다
